routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

/*
|--------------------------------------------------------------------------
| Login/Logout routes
|--------------------------------------------------------------------------
*/

Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
// Auth::routes();

/*
|--------------------------------------------------------------------------
| Front routes
|--------------------------------------------------------------------------
*/

// Route::get('/', ['as' => 'index', 'uses' => 'Front\IndexController@index']);
Route::get('',                                  ['as' => 'index',   'uses' => 'Frontend\IndexController@index']);
Route::get('category/{slug}/{sub_slug?}',       ['as' => 'category',   'uses' => 'Frontend\CategoryController@index']);
Route::get('product/{id}',                      ['as' => 'product',   'uses' => 'Frontend\ProductController@index']);
Route::get('page/{url}',                        ['as' => 'page',      'uses' => 'Frontend\PageController@index']);
Route::get('search',                            ['as' => 'search',    'uses' => 'Frontend\SearchController@index']);
Route::get('contact-us',                        ['as' => 'contact',   'uses' => 'Frontend\ContactController@index']);
Route::post('contact-us/send',                  ['as' => 'contact.send', 'uses' => 'Frontend\ContactController@send']);

Route::group(['prefix' => 'shop', 'as' => 'shop.'], function() {
    Route::get('/',                            ['as' => 'index',       'uses' => 'Frontend\ShopController@index']);
    Route::get('{shop_slug}',                  ['as' => 'view',        'uses' => 'Frontend\ShopController@view']);
    Route::get('{shop_slug}/products',         ['as' => 'products',    'uses' => 'Frontend\ShopController@products']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ShopController@rate']);
    });
});


Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('/',                             ['as' => 'index',   'uses' => 'Frontend\BlogController@index']);
    Route::get('tag/{tag_slug}',                ['as' => 'tag',     'uses' => 'Frontend\TagController@index']);
    Route::get('search',                        ['as' => 'search',  'uses' => 'Frontend\BlogController@search']);
    Route::get('{section_slug}',                ['as' => 'section', 'uses' => 'Frontend\SectionController@index']);
    Route::get('{section_slug}/{article_slug}', ['as' => 'article', 'uses' => 'Frontend\ArticleController@index']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('comment',  ['as' => 'comment', 'uses' => 'Frontend\ArticleController@comment']);
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ArticleController@rate']);
    });
});

/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::get('index', ['as' => 'index', 'uses' => 'Admin\IndexController@index']);
    Route::resource('user', 'Admin\UserController');
    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('sync', 'Admin\SyncController');
    Route::resource('shop', 'Admin\ShopController');
    Route::resource('image', 'Admin\ImageController');
    Route::resource('attribute_set', 'Admin\AttributeSetController');
    Route::resource('attribute', 'Admin\AttributeController');
    Route::resource('log', 'Admin\LogController');
    Route::resource('menu', 'Admin\MenuController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('section', 'Admin\SectionController');
    Route::resource('comment', 'Admin\CommentController');
    Route::resource('tag', 'Admin\TagController');
    Route::resource('page', 'Admin\PageController');
    Route::resource('setting', 'Admin\SettingController');

    Route::group(['prefix' => 'stat', 'as' => 'stat.'], function() {
        Route::get('products', ['as' => 'products', 'uses' => 'Admin\StatController@products']);
        Route::get('shops',    ['as' => 'shops',    'uses' => 'Admin\StatController@shops']);
        Route::get('articles', ['as' => 'articles', 'uses' => 'Admin\StatController@articles']);
    });

    Route::post('menu/order', ['as' => 'menu.order', 'uses' => 'Admin\MenuController@order']);
    Route::post('section/order', ['as' => 'section.order', 'uses' => 'Admin\SectionController@order']);

    Route::post('product/allproducts', ['as' => 'product.allproducts', 'uses' => 'Admin\ProductController@allProducts']);
    Route::post('category/allcategories', ['as' => 'category.allcategories', 'uses' => 'Admin\CategoryController@allCategories']);
    Route::post('attribute/allattributes', ['as' => 'attribute.allattributes', 'uses' => 'Admin\AttributeController@allAttributes']);
    Route::post('article/allarticles', ['as' => 'article.allarticles', 'uses' => 'Admin\ArticleController@allArticles']);

    Route::group(['prefix' => 'validate', 'middleware' => 'ajax'], function() {
        Route::get('user/email', ['as' => 'validate.user.email', 'uses' => 'Admin\Validation\UserController@email']);
        Route::get('shop/slug',  ['as' => 'validate.shop.slug',  'uses' => 'Admin\Validation\ShopController@slug']);
        Route::get('attribute/key',  ['as' => 'validate.attribute.key',  'uses' => 'Admin\Validation\AttributeController@key']);
        Route::get('category/slug',  ['as' => 'validate.category.slug',  'uses' => 'Admin\Validation\CategoryController@slug']);
        Route::get('article/slug',  ['as' => 'validate.article.slug',  'uses' => 'Admin\Validation\ArticleController@slug']);
        Route::get('section/slug',  ['as' => 'validate.section.slug',  'uses' => 'Admin\Validation\SectionController@slug']);
        Route::get('tag/slug',  ['as' => 'validate.tag.slug',  'uses' => 'Admin\Validation\TagController@slug']);
        Route::get('page/url',  ['as' => 'validate.page.url',  'uses' => 'Admin\Validation\PageController@url']);
    });
});

/*
|--------------------------------------------------------------------------
| Redirect everything other back
|--------------------------------------------------------------------------
*/
Route::any('{any}', function() {
    return redirect()->back();
})->where('any', '.*');

app/Shop.php
<?php

namespace App;

use Request;
use App\Helpers\CronSchedule;
use Illuminate\Database\Eloquent\SoftDeletes;

class Shop extends Model
{
    use SoftDeletes;

    protected $dates = ['delete_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug', 'feed_url', 'shop_url', 'shop_aff_url', 'attribute_set_id', 'category_id', 'cron_schedule', 'status'
    ];

    public function images()
    {
        return $this->morphToMany(Image::class, 'imageable')->withTimestamps();
    }

    public function getImageAttribute($value)
    {
        return $this->images()->first();
    }

    public function stats()
    {
        return $this->morphMany(Stat::class, 'statable');
    }

    public function getViewsAttribute()
    {
        $views = 0;
        foreach ($this->stats as $stat) {
            $views += $stat->views;
        }

        return $views;
    }

    public function getUniqueViewsAttribute()
    {
        return $this->stats()->count();
    }

    public function attribute_set()
    {
        return $this->belongsTo(AttributeSet::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function logs()
    {
        return $this->hasMany(Log::class);
    }

    public function getHumanReadableCronScheduleAttribute($value)
    {
        $schedule = CronSchedule::fromCronString($this->cron_schedule);

        return $schedule->asNaturalLanguage();
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = slugify($value);
    }

    public function getRatingAttribute()
    {
        return ($this->rate_count) ? $this->rate / $this->rate_count : 0;
    }
}

app/Http/Controllers/Admin/ShopController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use View;
use App\Shop;
use App\Category;
use App\AttributeSet;
use App\Http\Requests\ShopRequest;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\AdminController as AdminController;

class ShopController extends AdminController
{
    protected $breadcrumbs = [];

    public function __construct()
    {
        parent::__construct();
        $this->middleware('user.is.admin')->only('destroy');

        View::share('title', trans('admin_shop.index'));

        $this->breadcrumbs['admin.shop.index'] = trans('admin_shop.index');

        if ($this->breadcrumbs) {
            View::share('breadcrumbs', $this->breadcrumbs);
        }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shops = Shop::all();

        return view('admin.pages.shop.index', compact('shops'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $attribute_sets = AttributeSet::pluck('name', 'id');
        $categories = Category::pluck('name', 'id');

        return view('admin.pages.shop.create', compact('attribute_sets', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ShopRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ShopRequest $request)
    {
        $shop = Shop::create($request->all());
        $shop->images()->sync([$request->input('image_id')]);

        return redirect()->route('admin.shop.index')
            ->with('success', trans('admin_shop.success.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Shop  $shop
     * @return \Illuminate\Http\Response
     */
    public function show(Shop $shop)
    {
        return view('admin.pages.shop.show', compact('shop'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Shop  $shop
     * @return \Illuminate\Http\Response
     */
    public function edit(Shop $shop)
    {
        $attribute_sets = AttributeSet::pluck('name', 'id');
        $categories = Category::pluck('name', 'id');

        return view('admin.pages.shop.edit', compact('shop', 'attribute_sets', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\ShopRequest  $request
     * @param  Shop  $shop
     * @return \Illuminate\Http\Response
     */
    public function update(ShopRequest $request, Shop $shop)
    {
        $shop->update($request->all());
        $shop->images()->sync([$request->input('image_id')]);

        return redirect()->route('admin.shop.index')
            ->with('success', trans('admin_shop.success.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Shop  $shop
     * @return \Illuminate\Http\Response
     */
    public function destroy(Shop $shop)
    {
        $shop->delete();

        return redirect()->route('admin.shop.index')
            ->with('success', trans('admin_shop.success.delete'));
    }
}

app/Http/Controllers/Admin/Validation/ShopController.php
<?php

namespace App\Http\Controllers\Admin\Validation;

use App\Shop;
use Illuminate\Http\Request;

class ShopController extends Controller
{
    public function slug(Request $request)
    {
        if (! $request->has('slug')) {
            return response()->json(false);
        }

        $result = Shop::where('slug', '=', slugify($request->input('slug')));
        if ($this->isEdit) {
            $result = $result->where('id', '!=', $this->entityId);
        }

        $result = $result->pluck('id');

        if (!$result->isEmpty()) {
            return response()->json(false);
        }

        return response()->json(true);
    }
}

app/Http/Controllers/Frontend/ShopController.php
<?php

namespace App\Http\Controllers\Frontend;

use View;
use App\Stat;
use App\Shop;
use App\Http\Requests\ShopRateRequest;

class ShopController extends \App\Http\Controllers\FrontendController
{

    public function index()
    {
        $shops = Shop::where('status', 1)->paginate(config('constant.shop_page_limit'));

        return view('frontend.pages.shop.index', compact('shops'));
    }

    /**
     * @param $shop_slug
     * @return \Illuminate\Http\RedirectResponse|View
     */
    public function view($shop_slug)
    {
        $shop = Shop::where([
            ['slug', 'like', $shop_slug],
            ['status', '=', 1],
        ])->first();

        if (is_null($shop)) {
            return redirect()->route('index');
        }

        $carousel_products = $shop->products()->with(['images'])
            ->ordered()->paginate(config('constant.carousel_items'));

        $left_shops = Shop::where('status', 1)->get();
        View::share('left_shops', $left_shops);

        $stat = $shop->stats()->where('ip_address', 'like', request()->ip())->first();

        if ($stat) {
            $stat->views++;
            $stat->save();
        } else {
            $stat = new Stat([
                'views'         => 1,
                'ip_address'    => request()->ip()
            ]);
            $shop->stats()->save($stat);
        }

        return view('frontend.pages.shop.view', compact('shop', 'carousel_products'));
    }

    /**
     * @param $shop_slug
     * @return \Illuminate\Http\RedirectResponse|View
     */
    public function products($shop_slug)
    {
        $shop = Shop::where([
            ['slug', 'like', $shop_slug],
            ['status', '=', 1],
        ])->first();

        if (is_null($shop)) {
            return redirect()->route('index');
        }

        $products = $shop->products()->with(['images'])
            ->ordered()->paginate(config('constant.category_page_limit'));

        $left_shops = Shop::where('status', 1)->get();
        View::share('left_shops', $left_shops);

        return view('frontend.pages.shop.products', compact('shop', 'products'));
    }

    public function rate(ShopRateRequest $request)
    {
        $shop = Shop::find($request->input('shop_id'));

        if (is_null($shop)) {
            return response()->json([
                'success'   => false,
                'message'   => trans('frontend_shop.shop_error')
            ], 422);
        }

        $rated_shops = $request->cookie('rated_shops', []);

        if (! is_array($rated_shops)) {
            $rated_shops = [];
        }

        if (in_array($shop->id, $rated_shops)) {
            return response()->json([
                'success'   => false,
                'message'   => trans('frontend_shop.rate_error')
            ], 422);
        }
        $rated_shops[] = $shop->id;

        $shop->rate += $request->input('value');
        $shop->rate_count += 1;
        $shop->save();

        //set cookie expire time to one year
        $cookie = cookie('rated_shops', $rated_shops, 525600);

        return response()->json([
            'success'   => true,
            'rating'    => $shop->rating,
            'message'   => trans('frontend_shop.rate_success')
        ])->withCookie($cookie);
    }
}

resources/views/admin/pages/shop/_form.blade.php
<div class="box-body">
    <div class="form-group">
        {!! Form::label('name', trans('admin_shop.fields.name')) !!}
        {!! Form::text('name', null,
        ['class' => 'form-control', 'required' => 'required',
        'placeholder' => trans('admin_shop.fields.name')]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('slug', trans('admin_shop.fields.slug')) !!}
        {!! Form::text('slug', null,
        ['class' => 'form-control', 'required' => 'required',
        'placeholder' => trans('admin_shop.fields.slug')]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('feed_url', trans('admin_shop.fields.feed_url')) !!}
        {!! Form::text('feed_url', null,
        ['class' => 'form-control', 'required' => 'required',
        'placeholder' => trans('admin_shop.fields.feed_url')]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('shop_url', trans('admin_shop.fields.shop_url')) !!}
        {!! Form::text('shop_url', null,
        ['class' => 'form-control',
        'placeholder' => trans('admin_shop.fields.shop_url')]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('shop_aff_url', trans('admin_shop.fields.shop_aff_url')) !!}
        {!! Form::text('shop_aff_url', null,
        ['class' => 'form-control',
        'placeholder' => trans('admin_shop.fields.shop_aff_url')]) !!}
    </div>
     <div class="form-group">
        {!! Form::label('attribute_set_id', trans('admin_shop.fields.attribute_set')) !!}
        {!! Form::select('attribute_set_id', $attribute_sets, null,
        ['class' => 'form-control select2',  'required' => 'required']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('category_id', trans('admin_shop.fields.category')) !!}
        {!! Form::select('category_id', $categories, null,
        ['class' => 'form-control select2',  'required' => 'required']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('cron_schedule', trans('admin_shop.fields.cron_schedule')) !!}
        <div id="cron_selector"></div>
        {!! Form::hidden('cron_schedule', null) !!}
    </div>
    <div class="form-group">
        {!! Form::label('status', trans('admin_shop.fields.status')) !!}
        {!! Form::select('status', [0 => trans('common.disabled'), 1 => trans('common.enabled')], null,
        ['class' => 'form-control select2',  'required' => 'required']) !!}
    </div>
</div>
<!-- /.box-body -->

<div class="box-footer">
    <div class="box-footer">
        <a class="btn btn-default"
           href="{{ route('admin.shop.index') }}">
            {{ trans('common.button.back') }}
        </a>
        {!! Form::submit(trans("common.button.submit"),
            ['class' => 'btn btn-primary pull-right']) !!}
    </div>
</div>

@section('head_styles')
    {!! Html::style('css/admin/select2/select2.min.css') !!}
    {!! Html::style('css/admin/cron/jquery-cron.css') !!}
    {!! Html::style('css/admin/gentleSelect/jquery-gentleSelect.css') !!}
@endsection

@section('footer_script')
    {!! Html::script('js/admin/images.js') !!}
    {!! Html::script('js/jquery.validate.min.js') !!}
    {!! Html::script('js/admin/select2/select2.js') !!}
    {!! Html::script('js/admin/cron/jquery-cron-min.js') !!}
    {!! Html::script('js/admin/gentleSelect/jquery-gentleSelect-min.js') !!}
    {{-- {!! Html::script('js/jquery.validate.messages_bg.min.js') !!} --}}
    <script>
        jQuery(function($) {
            $('.shop-form').validate({
                rules: {
                    title: {
                        required: true,
                        maxlength: 255
                    },
                    slug: {
                        required: true,
                        maxlength: 255,
                        remote: '{{ route('admin.validate.shop.slug') }}'
                    },
                    feed_url: {
                        required: true,
                        url: true
                    },
                    shop_url: {
                        url: true
                    },
                    shop_aff_url: {
                        url: true
                    },
                    // attribute_set_id: {
                    //     required: true
                    // },
                    status: {
                        required: true
                    }
                },
                highlight: function(element) {
                    $(element).closest('.form-group').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-error');
                },
                errorPlacement: function(error, element) {
                    if(element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
        });

        $('.select2').select2();

        @if (!isset($shop))
            var initial = '0 3 * * 5';
        @else
            var initial = '{{ $shop->cron_schedule }}';
        @endif
        $('#cron_selector').cron({
            initial: initial,
            onChange: function() {
                $('#cron_schedule').val($(this).cron('value'));
            },
            useGentleSelect: true // default: false
        });
    </script>
@endsection

resources/views/admin/pages/shop/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
      {!! Form::open(['method' => 'POST', 'files' => true,
          'url' => route('admin.shop.store'),
          'class' => 'shop-form']) !!}
        <div class="col-md-8">
          <div class="widget">
              <div class="widget-head">
                <div class="pull-left">{{ trans('admin_shop.create') }}</div>
                <div class="widget-icons pull-right">
                  <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="widget-content">
                  <div class="padd">
                      <div class="form">
                        <!-- Edit profile form (not working)-->
                        <!-- form start -->
                        @include('admin.pages.shop._form')
                        <!-- form end -->
                      </div>
                  </div>
                  <div class="widget-foot">
                  <!-- Footer goes here -->
                  </div>
              </div>
          </div>
        </div>
        @include('admin.partials.right_form_image', isset($shop) ? ['record' => $shop] : [])
      {!! Form::close() !!}

      @include('admin.partials.modals.select_image')
      @include('admin.partials.modals.upload_image')
    </div>
@endsection

resources/views/admin/pages/shop/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        {!! Form::model($shop, ['method' => 'PATCH', 'files' => true,
            'url' => route('admin.shop.update', ['shop' => $shop]),
            'class' => 'shop-form']) !!}
        <div class="col-md-8">
            <div class="widget">
                <div class="widget-head">
                    <div class="pull-left">{{ trans('admin_shop.create') }}</div>
                    <div class="widget-icons pull-right">
                        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget-content">
                    <div class="padd">
                        <div class="form">
                            <!-- Edit profile form (not working)-->
                            <!-- form start -->
                        @include('admin.pages.shop._form')
                        <!-- form end -->
                        </div>
                    </div>
                    <div class="widget-foot">
                        <!-- Footer goes here -->
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.right_form_image', isset($shop) ? ['record' => $shop] : [])
        {!! Form::close() !!}

        @include('admin.partials.modals.select_image')
        @include('admin.partials.modals.upload_image')
    </div>
@endsection

resources/views/admin/pages/shop/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
      <div class="col-md-12">
        <div class="widget">
          <div class="widget-head">
            <div class="pull-left">{{ trans('admin_shop.all') }}</div>
              <div class="widget-icons pull-right">
                <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
              </div>
                  <a class="pull-right btn btn-xs btn-success"
                   href="{{ route('admin.shop.create') }}">
                    {{ trans('admin_shop.create') }}
                </a>
            <div class="clearfix"></div>
           </div>

            <div class="widget-content">
                <div class="padd">
                    <div class="page-tables">
                        <table id="shops" class="table table-striped table-bordered table-hover">
                          <thead>
                            <tr>
                                <th>{{ trans('admin_shop.columns.id') }}</th>
                                <th>{{ trans('admin_shop.columns.image') }}</th>
                                <th>{{ trans('admin_shop.columns.name') }}</th>
                                <th>{{ trans('admin_shop.columns.cron_schedule') }}</th>
                                <th>{{ trans('admin_shop.columns.updated_at') }}</th>
                                <th>{{ trans('admin_shop.columns.status') }}</th>
                                <th></th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($shops as $shop)
                            <tr>
                                <td>{{ $shop->id }}</td>
                                <td>
                                  @if($shop->image)
                                      {!! Html::image($shop->image->url,
                                          'Shop Image', ['width' => 30, 'height' => 30]) !!}
                                  @else
                                      {!! Html::image('assets/img/no-image.png',
                                       'Shop Image', ['width' => 30, 'height' => 30]) !!}
                                  @endif
                                </td>
                                <td>{{ $shop->name }}</td>
                                <td>{{ $shop->human_readable_cron_schedule }}</td>
                                <td>{{ $shop->updated_at }}</td>
                                <td>
                                    @if ($shop->status)
                                        <span class="label label-success"><i class="fa fa-check"></i> {{ trans('common.enabled') }}</span>
                                    @else
                                        <span class="label label-danger"><i class="fa fa-close"></i> {{ trans('common.disabled') }}</span>
                                    @endif
                                </td>
                                <td>
                                    <a class="btn btn-xs btn-success"
                                        href="{{ route('admin.shop.show',
                                        ['shop' => $shop->id]) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>

                                    <a class="btn btn-xs btn-warning"
                                        href="{{ route('admin.shop.edit',
                                        ['shop' => $shop->id]) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>

                                    <a class="btn btn-xs btn-danger"
                                        href="#destroyModal" data-toggle="modal"
                                        data-url="{{ route('admin.shop.destroy',
                                        ['shop' => $shop->id]) }}"
                                        data-text="{{ trans('common.destroy_shop',
                                        ['id' => $shop->id, 'email' => $shop->email]) }}">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                    </div>

                    <div class="widget-foot">
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>


    @include('admin.partials.modals.destroy')
@endsection

@section('footer_script')
    <script type="text/javascript">
        $(function () {
            $('#shops').DataTable({
                columnDefs: [{
                    orderable: false,
                    targets: [1, 6]
                }]
            });
        });
    </script>
@endsection