routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

/*
|--------------------------------------------------------------------------
| Login/Logout routes
|--------------------------------------------------------------------------
*/

Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
// Auth::routes();

/*
|--------------------------------------------------------------------------
| Front routes
|--------------------------------------------------------------------------
*/

// Route::get('/', ['as' => 'index', 'uses' => 'Front\IndexController@index']);
Route::get('',                                  ['as' => 'index',   'uses' => 'Frontend\IndexController@index']);
Route::get('category/{slug}/{sub_slug?}',       ['as' => 'category',   'uses' => 'Frontend\CategoryController@index']);
Route::get('product/{id}',                      ['as' => 'product',   'uses' => 'Frontend\ProductController@index']);
Route::get('page/{url}',                        ['as' => 'page',      'uses' => 'Frontend\PageController@index']);
Route::get('search',                            ['as' => 'search',    'uses' => 'Frontend\SearchController@index']);
Route::get('contact-us',                        ['as' => 'contact',   'uses' => 'Frontend\ContactController@index']);
Route::post('contact-us/send',                  ['as' => 'contact.send', 'uses' => 'Frontend\ContactController@send']);

Route::group(['prefix' => 'shop', 'as' => 'shop.'], function() {
    Route::get('/',                            ['as' => 'index',       'uses' => 'Frontend\ShopController@index']);
    Route::get('{shop_slug}',                  ['as' => 'view',        'uses' => 'Frontend\ShopController@view']);
    Route::get('{shop_slug}/products',         ['as' => 'products',    'uses' => 'Frontend\ShopController@products']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ShopController@rate']);
    });
});


Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('/',                             ['as' => 'index',   'uses' => 'Frontend\BlogController@index']);
    Route::get('tag/{tag_slug}',                ['as' => 'tag',     'uses' => 'Frontend\TagController@index']);
    Route::get('search',                        ['as' => 'search',  'uses' => 'Frontend\BlogController@search']);
    Route::get('{section_slug}',                ['as' => 'section', 'uses' => 'Frontend\SectionController@index']);
    Route::get('{section_slug}/{article_slug}', ['as' => 'article', 'uses' => 'Frontend\ArticleController@index']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('comment',  ['as' => 'comment', 'uses' => 'Frontend\ArticleController@comment']);
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ArticleController@rate']);
    });
});

/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::get('index', ['as' => 'index', 'uses' => 'Admin\IndexController@index']);
    Route::resource('user', 'Admin\UserController');
    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('sync', 'Admin\SyncController');
    Route::resource('shop', 'Admin\ShopController');
    Route::resource('image', 'Admin\ImageController');
    Route::resource('attribute_set', 'Admin\AttributeSetController');
    Route::resource('attribute', 'Admin\AttributeController');
    Route::resource('log', 'Admin\LogController');
    Route::resource('menu', 'Admin\MenuController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('section', 'Admin\SectionController');
    Route::resource('comment', 'Admin\CommentController');
    Route::resource('tag', 'Admin\TagController');
    Route::resource('page', 'Admin\PageController');
    Route::resource('setting', 'Admin\SettingController');

    Route::group(['prefix' => 'stat', 'as' => 'stat.'], function() {
        Route::get('products', ['as' => 'products', 'uses' => 'Admin\StatController@products']);
        Route::get('shops',    ['as' => 'shops',    'uses' => 'Admin\StatController@shops']);
        Route::get('articles', ['as' => 'articles', 'uses' => 'Admin\StatController@articles']);
    });

    Route::post('menu/order', ['as' => 'menu.order', 'uses' => 'Admin\MenuController@order']);
    Route::post('section/order', ['as' => 'section.order', 'uses' => 'Admin\SectionController@order']);

    Route::post('product/allproducts', ['as' => 'product.allproducts', 'uses' => 'Admin\ProductController@allProducts']);
    Route::post('category/allcategories', ['as' => 'category.allcategories', 'uses' => 'Admin\CategoryController@allCategories']);
    Route::post('attribute/allattributes', ['as' => 'attribute.allattributes', 'uses' => 'Admin\AttributeController@allAttributes']);
    Route::post('article/allarticles', ['as' => 'article.allarticles', 'uses' => 'Admin\ArticleController@allArticles']);

    Route::group(['prefix' => 'validate', 'middleware' => 'ajax'], function() {
        Route::get('user/email', ['as' => 'validate.user.email', 'uses' => 'Admin\Validation\UserController@email']);
        Route::get('shop/slug',  ['as' => 'validate.shop.slug',  'uses' => 'Admin\Validation\ShopController@slug']);
        Route::get('attribute/key',  ['as' => 'validate.attribute.key',  'uses' => 'Admin\Validation\AttributeController@key']);
        Route::get('category/slug',  ['as' => 'validate.category.slug',  'uses' => 'Admin\Validation\CategoryController@slug']);
        Route::get('article/slug',  ['as' => 'validate.article.slug',  'uses' => 'Admin\Validation\ArticleController@slug']);
        Route::get('section/slug',  ['as' => 'validate.section.slug',  'uses' => 'Admin\Validation\SectionController@slug']);
        Route::get('tag/slug',  ['as' => 'validate.tag.slug',  'uses' => 'Admin\Validation\TagController@slug']);
        Route::get('page/url',  ['as' => 'validate.page.url',  'uses' => 'Admin\Validation\PageController@url']);
    });
});

/*
|--------------------------------------------------------------------------
| Redirect everything other back
|--------------------------------------------------------------------------
*/
Route::any('{any}', function() {
    return redirect()->back();
})->where('any', '.*');

resources/views/admin/pages/page/_form.blade.php
<div class="box-body">
    <div class="form-group">
        {!! Form::label('title', trans('admin_page.fields.title')) !!}
        {!! Form::text('title', null,
        ['class' => 'form-control', 'required' => 'required',
        'placeholder' => trans('admin_page.fields.title')]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('url', trans('admin_page.fields.url')) !!}
        {!! Form::text('url', null,
        ['class' => 'form-control', 'required' => 'required',
        'placeholder' => trans('admin_page.fields.url')]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('content', trans('admin_page.fields.content')) !!}
        {!! Form::textarea('content', null,
        ['class' => 'form-control', 'rows' => '10',
        'required' => 'required',
        'placeholder' => trans('admin_page.fields.content')]) !!}
    </div>
    <div class="form-group">
        {!! Form::label('in_footer', trans('admin_page.fields.in_footer')) !!}
        {!! Form::select('in_footer', [1 => trans('common.yes'), 0 => trans('common.no')], null,
        ['class' => 'form-control select2',  'required' => 'required']) !!}
    </div>
</div>
<!-- /.box-body -->

<div class="box-footer">
    <div class="box-footer">
        <a class="btn btn-default"
           href="{{ route('admin.page.index') }}">
            {{ trans('common.button.back') }}
        </a>
        {!! Form::submit(trans("common.button.submit"),
            ['class' => 'btn btn-primary pull-right']) !!}
    </div>
</div>

@section('head_styles')
    {!! Html::style('css/admin/select2/select2.min.css') !!}
@endsection

@section('footer_script')
    {!! Html::script('js/admin/ckeditor/ckeditor.js') !!}
    {!! Html::script('js/jquery.validate.min.js') !!}
    {!! Html::script('js/admin/select2/select2.js') !!}
    <script>
        jQuery(function($) {
            $('.page-form').validate({
                rules: {
                    title: {
                        required: true,
                        maxlength: 255
                    },
                    url: {
                        required: true,
                        maxlength: 255,
                        remote: '{{ route('admin.validate.page.url') }}'
                    },
                    content: {
                        required: true
                    }
                },
                highlight: function(element) {
                    $(element).closest('.form-group').addClass('has-error');
                },
                unhighlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-error');
                },
                errorPlacement: function(error, element) {
                    if(element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
        });

        $('.select2').select2();

        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/admin/pages/page/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
      {!! Form::open(['method' => 'POST', 'files' => true,
          'url' => route('admin.page.store'),
          'class' => 'page-form']) !!}
        <div class="col-md-12">
          <div class="widget">
              <div class="widget-head">
                <div class="pull-left">{{ trans('admin_page.create') }}</div>
                <div class="widget-icons pull-right">
                  <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="widget-content">
                  <div class="padd">
                      <div class="form">
                        <!-- Edit profile form (not working)-->
                        <!-- form start -->
                        @include('admin.pages.page._form')
                        <!-- form end -->
                      </div>
                  </div>
                  <div class="widget-foot">
                  <!-- Footer goes here -->
                  </div>
              </div>
          </div>
        </div>
      {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/pages/page/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        {!! Form::model($page, ['method' => 'PATCH', 'files' => true,
            'url' => route('admin.page.update', ['page' => $page]),
            'class' => 'page-form']) !!}
        <div class="col-md-12">
            <div class="widget">
                <div class="widget-head">
                    <div class="pull-left">{{ trans('admin_page.create') }}</div>
                    <div class="widget-icons pull-right">
                        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget-content">
                    <div class="padd">
                        <div class="form">
                            <!-- Edit profile form (not working)-->
                            <!-- form start -->
                        @include('admin.pages.page._form')
                        <!-- form end -->
                        </div>
                    </div>
                    <div class="widget-foot">
                        <!-- Footer goes here -->
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/pages/page/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
      <div class="col-md-12">

        <div class="widget">
          <div class="widget-head">
            <div class="pull-left">{{ trans('admin_page.all') }}</div>
              <div class="widget-icons pull-right">
                <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
              </div>
                  <a class="pull-right btn btn-xs btn-success"
                   href="{{ route('admin.page.create') }}">
                    {{ trans('admin_page.create') }}
                </a>
            <div class="clearfix"></div>
           </div>

            <div class="widget-content">
                <div class="padd">
                    <div class="page-tables">
                        <table id="pages" class="table table-striped table-bordered table-hover">
                          <thead>
                            <tr>
                                <th>{{ trans('admin_page.columns.id') }}</th>
                                <th>{{ trans('admin_page.columns.title') }}</th>
                                <th>{{ trans('admin_page.columns.url') }}</th>
                                <th>{{ trans('admin_page.columns.in_footer') }}</th>
                                <th>{{ trans('admin_page.columns.updated_at') }}</th>
                                <th></th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($pages as $page)
                            <tr>
                                <td>{{ $page->id }}</td>
                                <td>{{ $page->title }}</td>
                                <td>{{ $page->url }}</td>
                                <td>
                                    @if ($page->in_footer)
                                        <span class="label label-success"><i class="fa fa-check"></i> {{ trans('common.yes') }}</span>
                                    @else
                                        <span class="label label-danger"><i class="fa fa-close"></i> {{ trans('common.no') }}</span>
                                    @endif
                                </td>
                                <td>{{ $page->updated_at }}</td>
                                <td>
                                    <a class="btn btn-xs btn-success"
                                        href="{{ route('admin.page.show',
                                        ['page' => $page->id]) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>

                                    <a class="btn btn-xs btn-warning"
                                        href="{{ route('admin.page.edit',
                                        ['page' => $page->id]) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>

                                    <a class="btn btn-xs btn-danger"
                                        href="#destroyModal" data-toggle="modal"
                                        data-url="{{ route('admin.page.destroy',
                                        ['page' => $page->id]) }}"
                                        data-text="{{ trans('common.destroy_page',
                                        ['id' => $page->id]) }}">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                    </div>

                    <div class="widget-foot">
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>


    @include('admin.partials.modals.destroy')
@endsection

@section('footer_script')
    <script type="text/javascript">
        $(function () {
            $('#pages').DataTable({
                columnDefs: [{
                    orderable: false,
                    targets: -1
                }]
            });
        });
    </script>
@endsection

resources/views/admin/pages/page/show.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="widget">
                <!-- Widget title -->
                <div class="widget-head">
                    <div class="pull-left">{!! trans('admin_page.show') !!}</div>
                    <div class="widget-icons pull-right">
                        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget-content">
                    <!-- Widget content -->
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <tr>
                                <th>{!! trans('admin_page.fields.title') !!}</th>
                                <td>{{ $page->title }}</td>
                            </tr>
                            <tr>
                                <th>{!! trans('admin_page.fields.url') !!}</th>
                                <td>{{ $page->url }}</td>
                            </tr>
                            <tr>
                                <th>{!! trans('admin_page.fields.in_footer') !!}</th>
                                <td>{{ $page->in_footer }}</td>
                            </tr>
                            <tr>
                                <th>{!! trans('admin_page.fields.content') !!}</th>
                                <td>{!! $page->content !!}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="widget-foot">
                        <a class="btn  btn-sm btn-default"
                           href="{{ route('admin.page.index') }}">
                            {{ trans('common.button.back') }}
                        </a>
                        <a href="{{ route('admin.page.edit', ['page' => $page->id]) }}" class="btn  btn-sm btn-primary pull-right"><b>{!! trans('admin_page.edit') !!}</b></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection