routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

/*
|--------------------------------------------------------------------------
| Login/Logout routes
|--------------------------------------------------------------------------
*/

Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
// Auth::routes();

/*
|--------------------------------------------------------------------------
| Front routes
|--------------------------------------------------------------------------
*/

// Route::get('/', ['as' => 'index', 'uses' => 'Front\IndexController@index']);
Route::get('',                                  ['as' => 'index',   'uses' => 'Frontend\IndexController@index']);
Route::get('category/{slug}/{sub_slug?}',       ['as' => 'category',   'uses' => 'Frontend\CategoryController@index']);
Route::get('product/{id}',                      ['as' => 'product',   'uses' => 'Frontend\ProductController@index']);
Route::get('page/{url}',                        ['as' => 'page',      'uses' => 'Frontend\PageController@index']);
Route::get('search',                            ['as' => 'search',    'uses' => 'Frontend\SearchController@index']);
Route::get('contact-us',                        ['as' => 'contact',   'uses' => 'Frontend\ContactController@index']);
Route::post('contact-us/send',                  ['as' => 'contact.send', 'uses' => 'Frontend\ContactController@send']);

Route::group(['prefix' => 'shop', 'as' => 'shop.'], function() {
    Route::get('/',                            ['as' => 'index',       'uses' => 'Frontend\ShopController@index']);
    Route::get('{shop_slug}',                  ['as' => 'view',        'uses' => 'Frontend\ShopController@view']);
    Route::get('{shop_slug}/products',         ['as' => 'products',    'uses' => 'Frontend\ShopController@products']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ShopController@rate']);
    });
});


Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('/',                             ['as' => 'index',   'uses' => 'Frontend\BlogController@index']);
    Route::get('tag/{tag_slug}',                ['as' => 'tag',     'uses' => 'Frontend\TagController@index']);
    Route::get('search',                        ['as' => 'search',  'uses' => 'Frontend\BlogController@search']);
    Route::get('{section_slug}',                ['as' => 'section', 'uses' => 'Frontend\SectionController@index']);
    Route::get('{section_slug}/{article_slug}', ['as' => 'article', 'uses' => 'Frontend\ArticleController@index']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('comment',  ['as' => 'comment', 'uses' => 'Frontend\ArticleController@comment']);
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ArticleController@rate']);
    });
});

/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::get('index', ['as' => 'index', 'uses' => 'Admin\IndexController@index']);
    Route::resource('user', 'Admin\UserController');
    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('sync', 'Admin\SyncController');
    Route::resource('shop', 'Admin\ShopController');
    Route::resource('image', 'Admin\ImageController');
    Route::resource('attribute_set', 'Admin\AttributeSetController');
    Route::resource('attribute', 'Admin\AttributeController');
    Route::resource('log', 'Admin\LogController');
    Route::resource('menu', 'Admin\MenuController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('section', 'Admin\SectionController');
    Route::resource('comment', 'Admin\CommentController');
    Route::resource('tag', 'Admin\TagController');
    Route::resource('page', 'Admin\PageController');
    Route::resource('setting', 'Admin\SettingController');

    Route::group(['prefix' => 'stat', 'as' => 'stat.'], function() {
        Route::get('products', ['as' => 'products', 'uses' => 'Admin\StatController@products']);
        Route::get('shops',    ['as' => 'shops',    'uses' => 'Admin\StatController@shops']);
        Route::get('articles', ['as' => 'articles', 'uses' => 'Admin\StatController@articles']);
    });

    Route::post('menu/order', ['as' => 'menu.order', 'uses' => 'Admin\MenuController@order']);
    Route::post('section/order', ['as' => 'section.order', 'uses' => 'Admin\SectionController@order']);

    Route::post('product/allproducts', ['as' => 'product.allproducts', 'uses' => 'Admin\ProductController@allProducts']);
    Route::post('category/allcategories', ['as' => 'category.allcategories', 'uses' => 'Admin\CategoryController@allCategories']);
    Route::post('attribute/allattributes', ['as' => 'attribute.allattributes', 'uses' => 'Admin\AttributeController@allAttributes']);
    Route::post('article/allarticles', ['as' => 'article.allarticles', 'uses' => 'Admin\ArticleController@allArticles']);

    Route::group(['prefix' => 'validate', 'middleware' => 'ajax'], function() {
        Route::get('user/email', ['as' => 'validate.user.email', 'uses' => 'Admin\Validation\UserController@email']);
        Route::get('shop/slug',  ['as' => 'validate.shop.slug',  'uses' => 'Admin\Validation\ShopController@slug']);
        Route::get('attribute/key',  ['as' => 'validate.attribute.key',  'uses' => 'Admin\Validation\AttributeController@key']);
        Route::get('category/slug',  ['as' => 'validate.category.slug',  'uses' => 'Admin\Validation\CategoryController@slug']);
        Route::get('article/slug',  ['as' => 'validate.article.slug',  'uses' => 'Admin\Validation\ArticleController@slug']);
        Route::get('section/slug',  ['as' => 'validate.section.slug',  'uses' => 'Admin\Validation\SectionController@slug']);
        Route::get('tag/slug',  ['as' => 'validate.tag.slug',  'uses' => 'Admin\Validation\TagController@slug']);
        Route::get('page/url',  ['as' => 'validate.page.url',  'uses' => 'Admin\Validation\PageController@url']);
    });
});

/*
|--------------------------------------------------------------------------
| Redirect everything other back
|--------------------------------------------------------------------------
*/
Route::any('{any}', function() {
    return redirect()->back();
})->where('any', '.*');

app/Article.php
<?php

namespace App;

use Request;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use SoftDeletes;

    protected $dates = ['delete_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'slug', 'description', 'content', 'section_id'
    ];

    public function images()
    {
        return $this->morphToMany(Image::class, 'imageable')->withTimestamps();
    }

    public function getImageAttribute($value)
    {
        return $this->images()->first();
    }

    public function section()
    {
        return $this->belongsTo(Section::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function stats()
    {
        return $this->morphMany(Stat::class, 'statable');
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = slugify($value);
    }

    public function getTagListAttribute()
    {
        return $this->tags()->pluck('id')->toArray();
    }

    public function getApprovedCommentsAttribute()
    {
        return $this->comments()->where('approved', '=', '1')->get();
    }

    public function getRatingAttribute()
    {
        return ($this->rate_count) ? $this->rate / $this->rate_count : 0;
    }

    public function getViewsAttribute()
    {
        $views = 0;
        foreach ($this->stats as $stat) {
            $views += $stat->views;
        }

        return $views;
    }

    public function getUniqueViewsAttribute()
    {
        return $this->stats()->count();
    }
}

app/Http/Controllers/Frontend/ArticleController.php
<?php

namespace App\Http\Controllers\Frontend;

use Auth;
use App\Stat;
use App\Article;
use App\Section;
use App\Http\Requests\ArticleRateRequest;
use App\Http\Requests\ArticleCommentRequest;

class ArticleController extends \App\Http\Controllers\FrontendController
{
    /**
     * @param string $section_slug
     * @param string $article_slug
     * @return \Illuminate\Http\Response
     */
    public function index($section_slug, $article_slug)
    {
        $section = Section::where('slug', $section_slug)->first();

        if (is_null($section)) {
            return redirect()->route('index');
        }

        $article = Article::where('slug', $article_slug)
            ->where('section_id', $section->id)->first();

        if (is_null($article)) {
            return redirect()->route('index');
        }

        $stat = $article->stats()->where('ip_address', 'like', request()->ip())->first();

        if ($stat) {
            $stat->views++;
            $stat->save();
        } else {
            $stat = new Stat([
                'views'         => 1,
                'ip_address'    => request()->ip()
            ]);
            $article->stats()->save($stat);
        }

        return view('frontend.pages.article', compact('article'));
    }

    public function comment(ArticleCommentRequest $request)
    {
        $article = Article::find($request->input('article_id'));

        if (is_null($article)) {
            return response()->json([
                'success'   => false,
                'message'   => trans('frontend_blog.article_error')
            ], 422);
        }

        $article->comments()->create($request->all());

        return response()->json([
            'success'   => true,
            'message'   => trans('frontend_blog.comment_success')
        ]);
    }

    public function rate(ArticleRateRequest $request)
    {
        $article = Article::find($request->input('article_id'));

        if (is_null($article)) {
            return response()->json([
                'success'   => false,
                'message'   => trans('frontend_blog.article_error')
            ], 422);
        }

        $rated_articles = $request->cookie('rated_articles', []);

        if (! is_array($rated_articles)) {
            $rated_articles = [];
        }

        if (in_array($article->id, $rated_articles)) {
            return response()->json([
                'success'   => false,
                'message'   => trans('frontend_blog.rate_error')
            ], 422);
        }
        $rated_articles[] = $article->id;

        $article->rate += $request->input('value');
        $article->rate_count += 1;
        $article->save();

        //set cookie expire time to one year
        $cookie = cookie('rated_articles', $rated_articles, 525600);

        return response()->json([
            'success'   => true,
            'rating'    => $article->rating,
            'message'   => trans('frontend_blog.rate_success')
        ])->withCookie($cookie);
    }
}

app/Http/Controllers/Frontend/BlogController.php
<?php

namespace App\Http\Controllers\Frontend;

use View;
use App\Article;
use Illuminate\Http\Request;

class BlogController extends \App\Http\Controllers\FrontendController
{
    /**
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = trans('frontend_blog.index');

        $articles = Article::with(['section', 'images', 'user', 'tags'])
            ->ordered()->paginate(config('constant.articles_page_limit'));

        return view('frontend.pages.section', compact('title', 'articles'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|View
     */
    public function search(Request $request)
    {
        if (!$request->has('query')) {
            return redirect()->route('index');
        }

        $title = trans('frontend_blog.search_for') . ' ' . $request->input('query');

        $articles = Article::with(['section', 'images', 'user', 'tags'])
            ->orWhere('title', 'like', '%' . $request->input('query') . '%')
            ->orWhere('slug', 'like', '%' . $request->input('query') . '%')
            ->orWhere('description', 'like', '%' . $request->input('query') . '%')
            ->orWhere('content', 'like', '%' . $request->input('query') . '%')
            ->ordered()->paginate(config('constant.articles_page_limit'));

        return view('frontend.pages.section', compact('title', 'articles'));
    }
}

app/Http/Controllers/Frontend/CategoryController.php
<?php

namespace App\Http\Controllers\Frontend;

use View;
use App\Product;
use App\Category;

class CategoryController extends \App\Http\Controllers\FrontendController
{
    /**
     * @param $slug
     * @param null $sub_slug
     * @return \Illuminate\Http\RedirectResponse|View
     */
    public function index($slug, $sub_slug = null)
    {
        $category = Category::where('slug', $slug)->first();
        $sub_category = null;

        if (is_null($category)) {
            return redirect()->route('index');
        }

        View::share('parent_category', $category);

        if (!$sub_slug) {
            $ids[] = $category->id;
            foreach ($category->childrens as $child) {
                $ids[] = $child->id;
            }

            $products = Product::with(['image'])->whereHas('categories', function($query) use($ids) {
                $query->whereIn('id', $ids);
            })->ordered()->paginate(config('constant.category_page_limit'));
        } else {
            $sub_category = Category::where([
                ['slug', 'like', $sub_slug],
                ['parent_category_id', '=', $category->id]
            ])->first();

            if (is_null($sub_category)) {
                return redirect()->route('index');
            }

            $products = $sub_category->products()->with(['images'])
                ->ordered()->paginate(config('constant.category_page_limit'));

            $category = $sub_category;
        }

        $carousel_products = Product::with(['image'])
            ->inRandomOrder()->limit(config('constant.carousel_items'))
            ->get();

        return view('frontend.pages.category', compact('category', 'products', 'carousel_products'));
    }
}

app/Http/Controllers/Frontend/ContactController.php
<?php

namespace App\Http\Controllers\Frontend;

use Mail;
use App\Http\Requests\ContactRequest;

class ContactController extends \App\Http\Controllers\FrontendController
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('frontend.pages.contact');
    }

    public function send(ContactRequest $request)
    {
        Mail::raw($request->input('comment'), function($message) use ($request) {

            $message->from($request->input('email'), $request->input('name'));

            $message->to(\App\Setting::get('contact_email'));

            $message->subject(trans('frontend_contact.contact_subject'));

        });

        return redirect()->route('contact')
            ->with('success', trans('frontend_contact.contact_success'));
    }
}

app/Http/Controllers/Frontend/IndexController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Product;

class IndexController extends \App\Http\Controllers\FrontendController
{
    /**
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with(['image'])
            ->latest()->limit(config('constant.index_page_products'))
            ->get();

        $carousel_products = Product::with(['image'])
            ->inRandomOrder()->limit(config('constant.carousel_items'))
            ->get();

        return view('frontend.pages.index', compact('products', 'carousel_products'));
    }
}

app/Http/Controllers/Frontend/PageController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Page;

class PageController extends \App\Http\Controllers\FrontendController
{

    /**
     * @param $url
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index($url)
    {
        $page = Page::where('url', $url)->first();

        if (is_null($page)) {
            return redirect()->route('index');
        }

        return view('frontend.pages.page', compact('page'));
    }
}

resources/views/frontend/partials/article.blade.php
<div class="entry">
    <h2>
        <a href="{{ route('blog.article',
                        [
                            'section_slug' => $article->section->slug,
                            'article_slug' => $article->slug,
                        ]) }}">
            {{ $article->title }}
        </a>
    </h2>
    <!-- Meta details. Calendar, Author, Category and comments-->
    <div class="meta clearfix">
        <i class="fa fa-calendar"></i> {{ $article->updated_at->format('Y-m-d') }}
        <i class="fa fa-user"></i> {{ $article->user->name }}
        <i class="fa fa-folder-open"></i> <a href="{{ route('blog.section', ['section_slug' => $article->section->slug]) }}">{{ $article->section->title }}</a>
        <span class="pull-right"><i class="fa fa-comment"></i> {{ $article->approved_comments->count() }} {{ trans_choice('frontend_blog.comments', $article->approved_comments->count()) }}</span>
    </div>

    <!-- Thumbnail -->
    <div class="bthumb">
        <a href="{{ route('blog.article',
                        [
                            'section_slug' => $article->section->slug,
                            'article_slug' => $article->slug,
                        ]) }}">
            <img src="{{ $article->image->url }}" alt="" class="img-responsive" />
        </a>
    </div>

    {!! $article->description !!}
    <div class="button">
        <a href="{{ route('blog.article',
                        [
                            'section_slug' => $article->section->slug,
                            'article_slug' => $article->slug,
                        ]) }}">
            {{ trans('common.read_more') }}
        </a>
    </div>
</div>

resources/views/frontend/partials/carousel_slider.blade.php
<!-- Recent Item -->
<div class="recent-item">
    <div class="custom-nav">
        <a class="prev"><i class="fa fa-chevron-left br-lblue"></i></a>
        <a class="next"><i class="fa fa-chevron-right br-lblue"></i></a>
    </div>
    <div id="owl-recent" class="owl-carousel">
        <!-- Item -->
        @foreach($products as $product)
            <div class="item">
                <a href="{{ route('product', ['id' => $product->id]) }}">
                    @if($product->image)
                        <img src="{{ $product->image->url }}" alt="" class="img-responsive" />
                    @else
                        {!! Html::image('uploads/images/no-image.png',
                         'Product Image', ['width' => 140, 'height' => 140, 'class' => 'img-responsive']) !!}
                    @endif
                </a>
                <!-- Heading -->
                <h4>
                    <a href="{{ route('product', ['id' => $product->id]) }}">
                        {{ str_limit($product->getData(\App\Product::NAME), 15) }}
                        <span class="pull-right">
                            {{ number_format($product->getData(\App\Product::PRICE), 2) }} {{ trans('common.currency_symbol') }}
                        </span>
                    </a>
                </h4>
                <div class="clearfix"></div>
                <!-- Paragraph -->
                <p class="item-name">{{ str_limit($product->getData('description'), 25) }}</p>
            </div>
        @endforeach
    </div>
</div>

resources/views/frontend/partials/flex_slider.blade.php
<div class="container flex-main">
    <div class="row">
        <div class="col-md-12">
            <div class="flex-image flexslider">
                <ul class="slides">
                    <!-- Each slide should be enclosed inside li tag. -->
                    <!-- Slide #1 -->
                    <li>
                        <!-- Image -->
                        <img src="img/photos/slider1.jpg" alt=""/>
                        <!-- Caption -->
                        <div class="flex-caption">
                            <!-- Title -->
                            <h3>Levi's T-Shirt - <span class="color">Just $49</span></h3>
                            <!-- Para -->
                            <p>Ut commodo ullamcorper risus nec mattis. Fusce imperdiet ornare dignissim. Donec aliquet convallis tortor, et placerat quam posuere posuere. Morbi tincidunt posuere turpis eu laoreet. </p>
                            <div class="button">
                                <a href="single-item.html">Buy Now</a>
                            </div>
                        </div>
                    </li>

                    <!-- Slide #2 -->
                    <li>
                        <img src="img/photos/slider2.jpg" alt=""/>
                        <div class="flex-caption">
                            <!-- Title -->
                            <h3>Denim Jeans - <span class="color">Just $149</span></h3>
                            <!-- Para -->
                            <p>Ut commodo ullamcorper risus nec mattis. Fusce imperdiet ornare dignissim. Donec aliquet convallis tortor, et placerat quam posuere posuere. Morbi tincidunt posuere turpis eu laoreet. </p>
                            <div class="button">
                                <a href="single-item.html">Buy Now</a>
                            </div>
                        </div>
                    </li>

                    <li>
                        <img src="img/photos/slider3.jpg" alt=""/>
                        <div class="flex-caption">
                            <!-- Title -->
                            <h3>Polo Shirts - <span class="color">Just $79</span></h3>
                            <!-- Para -->
                            <p>Ut commodo ullamcorper risus nec mattis. Fusce imperdiet ornare dignissim. Donec aliquet convallis tortor, et placerat quam posuere posuere. Morbi tincidunt posuere turpis eu laoreet. </p>
                            <div class="button">
                                <a href="single-item.html">Buy Now</a>
                            </div>
                        </div>
                    </li>

                    <li>
                        <img src="img/photos/slider4.jpg" alt=""/>
                        <div class="flex-caption">
                            <!-- Title -->
                            <h3>Raymonds Suitings - <span class="color">Just $449</span></h3>
                            <!-- Para -->
                            <p>Ut commodo ullamcorper risus nec mattis. Fusce imperdiet ornare dignissim. Donec aliquet convallis tortor, et placerat quam posuere posuere. Morbi tincidunt posuere turpis eu laoreet. </p>
                            <div class="button">
                                <a href="single-item.html">Buy Now</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/frontend/partials/head.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<!-- Title and other stuffs -->
<title>{{ isset($title) ? $title : config('app.name', 'Online Catalog') }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">

<!-- Favicon -->
<link rel="shortcut icon" href="img/favicon/favicon.png">

<!-- Stylesheets -->
{!! Html::style('css/bootstrap.min.css') !!}
<!-- Font awesome icon -->
{!! Html::style('css/font-awesome.min.css') !!}
{!! Html::style('css/font-awesome-animation.min.css') !!}

{!! Html::style('css/frontend/flexslider.css') !!}
{!! Html::style('css/frontend/owl.carousel.css') !!}
{!! Html::style('css/frontend/style.css') !!}
{!! Html::style('css/frontend/sidebar-nav.css') !!}

@php ($style = !is_null(Setting::get('frontend_color')) ? Setting::get('frontend_color') : 'blue')
{!! Html::style("css/frontend/$style.css") !!}

<!-- Favicon -->
<link rel="shortcut icon" href="img/favicon/favicon.png">

@yield('head_styles')

resources/views/frontend/partials/header.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <!-- Logo. Use class "color" to add color to the text. -->
            <div class="logo">
                <h1>
                    <a href="{{ route('index') }}">
                        <span class="color bold">
                          @if(Setting::get('site_name'))
                                {{ Setting::get('site_name') }}
                            @else
                                {{ trans('common.index') }}
                            @endif
                        </span>
                    </a>
                </h1>
                <p class="meta">
                    @if(Setting::get('site_description'))
                        {{ Setting::get('site_description') }}
                    @else
                        {{ trans('common.desc') }}
                    @endif
                </p>
            </div>
        </div>
        <div class="col-md-4 col-md-offset-4">
        {!! Form::open(['method' => 'GET', 'url' => route('search')]) !!}
            <div class="input-group">
                <input type="text" name="q" class="form-control" value="{{ app('request')->input('q') }}" id="header_search" placeholder="{{ trans('common.search_products') }}">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">{{ trans('common.search') }}</button>
                </span>
            </div>
        {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/frontend/partials/left_sidebar.blade.php
@if (isset($parent_category))
    <h5 class="title">{{ trans('common.categories') }}</h5>
    <!-- Sidebar navigation -->
    <nav>
        <ul id="nav">
            @foreach($parent_category->childrens as $children)
                <li>
                    <a href="{{ route('category', ['slug' => $parent_category->slug, 'sub_slug' => $children->slug]) }}">
                        {{ $children->name }}
                    </a>
                </li>
            @endforeach

        </ul>
    </nav>
    <br />
    <!-- Sidebar items (featured items)-->
@endif

@if (isset($left_shops))
    <h5 class="title">{{ trans('common.shops') }}</h5>
    <!-- Sidebar navigation -->
    <nav>
        <ul id="nav">
            @foreach($left_shops as $left_shop)
                <li>
                    <a href="{{ route('shop.view', ['shop_slug' => $left_shop->slug]) }}">
                        {{ $left_shop->name }}
                    </a>
                </li>
            @endforeach

        </ul>
    </nav>
    <br />
    <!-- Sidebar items (featured items)-->
@endif

<div class="sidebar-items">
    <h5 class="title">Featured Items</h5>

    <!-- Item #1 -->
    <div class="sitem">
        <!-- Don't forget the class "onethree-left" and "onethree-right" -->
        <div class="onethree-left">
            <!-- Image -->
            <a href="single-item.html"><img src="{{ asset('img/photos/2.png') }}" alt="" class="img-responsive" /></a>
        </div>
        <div class="onethree-right">
            <!-- Title -->
            <a href="single-item.html">HTC One V</a>
            <!-- Para -->
            <p>Aenean ullamcorper justo tincidunt justo aliquet.</p>
            <!-- Price -->
            <p class="bold">$199</p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

resources/views/frontend/partials/navigation.blade.php
<div class="container">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <ul class="nav navbar-nav">
            @foreach($menus as $menu)
                <li class="@if(request()->is($menu->url . '*')) active @endif"><a href="{{ url($menu->url) }}">{{ $menu->title }}</a></li>
            @endforeach
        </ul>
    </nav>
</div>

resources/views/frontend/partials/right_sidebar.blade.php
<div class="sidebar">
    <div class="widget">
        <h4>{{ trans('common.searching') }}</h4>
        {!! Form::open(['url' => route('blog.search'), 'method' => 'GET', 'class' => 'form-inline search-form']) !!}
        <div class="form-group">
            {!! Form::text('query', null,
            ['class' => 'form-control',
            'placeholder' => trans('common.searching')]) !!}
        </div>

        {!! Form::submit(trans('common.search'),
            ['class' => 'btn btn-default']) !!}
        {!! Form::close() !!}
    </div>

    @if (isset($right_sections))
        <!-- Widget -->
        <div class="widget">
            <h4>{{ trans('common.sections') }}</h4>
            <ul>
                @foreach($right_sections as $right_section)
                    <li>
                        <a href="{{ route('blog.section', ['section_slug' => $right_section->slug]) }}">
                            {{ $right_section->title }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

    @if($right_recent_articles)
        <div class="widget">
            <h4>{{ trans('common.recent_articles') }}</h4>
            <ul>
                @foreach($right_recent_articles as $right_recent_article)
                    <li>
                        <a href="{{ route('blog.article',
                            [
                                'section_slug' => $right_recent_article->section->slug,
                                'article_slug' => $right_recent_article->slug,
                            ]) }}">
                            {{ $right_recent_article->title }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </div>
    @endif
</div>