routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

/*
|--------------------------------------------------------------------------
| Login/Logout routes
|--------------------------------------------------------------------------
*/

Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
// Auth::routes();

/*
|--------------------------------------------------------------------------
| Front routes
|--------------------------------------------------------------------------
*/

// Route::get('/', ['as' => 'index', 'uses' => 'Front\IndexController@index']);
Route::get('',                                  ['as' => 'index',   'uses' => 'Frontend\IndexController@index']);
Route::get('category/{slug}/{sub_slug?}',       ['as' => 'category',   'uses' => 'Frontend\CategoryController@index']);
Route::get('product/{id}',                      ['as' => 'product',   'uses' => 'Frontend\ProductController@index']);
Route::get('page/{url}',                        ['as' => 'page',      'uses' => 'Frontend\PageController@index']);
Route::get('search',                            ['as' => 'search',    'uses' => 'Frontend\SearchController@index']);
Route::get('contact-us',                        ['as' => 'contact',   'uses' => 'Frontend\ContactController@index']);
Route::post('contact-us/send',                  ['as' => 'contact.send', 'uses' => 'Frontend\ContactController@send']);

Route::group(['prefix' => 'shop', 'as' => 'shop.'], function() {
    Route::get('/',                            ['as' => 'index',       'uses' => 'Frontend\ShopController@index']);
    Route::get('{shop_slug}',                  ['as' => 'view',        'uses' => 'Frontend\ShopController@view']);
    Route::get('{shop_slug}/products',         ['as' => 'products',    'uses' => 'Frontend\ShopController@products']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ShopController@rate']);
    });
});


Route::group(['prefix' => 'blog', 'as' => 'blog.'], function() {
    Route::get('/',                             ['as' => 'index',   'uses' => 'Frontend\BlogController@index']);
    Route::get('tag/{tag_slug}',                ['as' => 'tag',     'uses' => 'Frontend\TagController@index']);
    Route::get('search',                        ['as' => 'search',  'uses' => 'Frontend\BlogController@search']);
    Route::get('{section_slug}',                ['as' => 'section', 'uses' => 'Frontend\SectionController@index']);
    Route::get('{section_slug}/{article_slug}', ['as' => 'article', 'uses' => 'Frontend\ArticleController@index']);

    Route::group(['middleware' => 'ajax'], function() {
        Route::post('comment',  ['as' => 'comment', 'uses' => 'Frontend\ArticleController@comment']);
        Route::post('rate',     ['as' => 'rate',    'uses' => 'Frontend\ArticleController@rate']);
    });
});

/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::get('index', ['as' => 'index', 'uses' => 'Admin\IndexController@index']);
    Route::resource('user', 'Admin\UserController');
    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('sync', 'Admin\SyncController');
    Route::resource('shop', 'Admin\ShopController');
    Route::resource('image', 'Admin\ImageController');
    Route::resource('attribute_set', 'Admin\AttributeSetController');
    Route::resource('attribute', 'Admin\AttributeController');
    Route::resource('log', 'Admin\LogController');
    Route::resource('menu', 'Admin\MenuController');
    Route::resource('article', 'Admin\ArticleController');
    Route::resource('section', 'Admin\SectionController');
    Route::resource('comment', 'Admin\CommentController');
    Route::resource('tag', 'Admin\TagController');
    Route::resource('page', 'Admin\PageController');
    Route::resource('setting', 'Admin\SettingController');

    Route::group(['prefix' => 'stat', 'as' => 'stat.'], function() {
        Route::get('products', ['as' => 'products', 'uses' => 'Admin\StatController@products']);
        Route::get('shops',    ['as' => 'shops',    'uses' => 'Admin\StatController@shops']);
        Route::get('articles', ['as' => 'articles', 'uses' => 'Admin\StatController@articles']);
    });

    Route::post('menu/order', ['as' => 'menu.order', 'uses' => 'Admin\MenuController@order']);
    Route::post('section/order', ['as' => 'section.order', 'uses' => 'Admin\SectionController@order']);

    Route::post('product/allproducts', ['as' => 'product.allproducts', 'uses' => 'Admin\ProductController@allProducts']);
    Route::post('category/allcategories', ['as' => 'category.allcategories', 'uses' => 'Admin\CategoryController@allCategories']);
    Route::post('attribute/allattributes', ['as' => 'attribute.allattributes', 'uses' => 'Admin\AttributeController@allAttributes']);
    Route::post('article/allarticles', ['as' => 'article.allarticles', 'uses' => 'Admin\ArticleController@allArticles']);

    Route::group(['prefix' => 'validate', 'middleware' => 'ajax'], function() {
        Route::get('user/email', ['as' => 'validate.user.email', 'uses' => 'Admin\Validation\UserController@email']);
        Route::get('shop/slug',  ['as' => 'validate.shop.slug',  'uses' => 'Admin\Validation\ShopController@slug']);
        Route::get('attribute/key',  ['as' => 'validate.attribute.key',  'uses' => 'Admin\Validation\AttributeController@key']);
        Route::get('category/slug',  ['as' => 'validate.category.slug',  'uses' => 'Admin\Validation\CategoryController@slug']);
        Route::get('article/slug',  ['as' => 'validate.article.slug',  'uses' => 'Admin\Validation\ArticleController@slug']);
        Route::get('section/slug',  ['as' => 'validate.section.slug',  'uses' => 'Admin\Validation\SectionController@slug']);
        Route::get('tag/slug',  ['as' => 'validate.tag.slug',  'uses' => 'Admin\Validation\TagController@slug']);
        Route::get('page/url',  ['as' => 'validate.page.url',  'uses' => 'Admin\Validation\PageController@url']);
    });
});

/*
|--------------------------------------------------------------------------
| Redirect everything other back
|--------------------------------------------------------------------------
*/
Route::any('{any}', function() {
    return redirect()->back();
})->where('any', '.*');

resources/views/admin/partials/breadcrumbs.blade.php
  <div class="page-head">
    <h2 class="pull-left"><i class="fa fa-bookmark"></i> {{ $title }}</h2>
    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
      <a href="{{ route('admin.index') }}"><i class="fa fa-home"></i> {{ trans('admin_header.home') }}</a> 
      <!-- Divider -->
      @if (isset($breadcrumbs))
        @foreach ($breadcrumbs as $k => $v)
            <span class="divider">/</span> 
          <a href='{{ route("{$k}") }}' class="bread-current">{{ $v }}</a>
        @endforeach
      @endif

    </div>
    <div class="clearfix"></div>
  </div>

resources/views/admin/partials/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @foreach ($errors->all() as $error)
            <div><i class="icon fa fa-ban"></i> {{ $error }}</div>
        @endforeach
    </div>
@endif

resources/views/admin/partials/fixed_navbar.blade.php
<div class="navbar navbar-fixed-top bs-docs-nav" role="banner">
  
    <div class="conjtainer">
      <!-- Menu button for smallar screens -->
      <div class="navbar-header">
          <button class="navbar-toggle btn-navbar" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
            <span>{{ trans('admin_fixed_navbar.menu') }}</span>
          </button>
          <!-- Site name for smallar screens -->
          <a href="index.html" class="navbar-brand hidden-lg">{{ trans('admin_fixed_navbar.catalog') }}</a>
        </div>

      <!-- Navigation starts -->
      <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <!-- Links -->
        <ul class="nav navbar-nav pull-right">
          <li class="dropdown pull-right">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
              <i class="fa fa-user"></i> {{ Auth::user()->name }} <b class="caret"></b>
            </a>
            
            <!-- Dropdown menu -->
            <ul class="dropdown-menu">
              <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out"></i> {{ trans('admin_fixed_navbar.logout') }}</a></li>
            </ul>
          </li>
          
        </ul>
      </nav>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          {{ csrf_field() }}
      </form>
    </div>
</div>

resources/views/admin/partials/footer.blade.php
<!-- Footer starts -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
            <!-- Copyright info -->
            <p class="copy">Copyright &copy; {{ \Carbon\Carbon::now()->format('Y') }} | <a href="#">Online Catalog</a> </p>
      </div>
    </div>
  </div>
</footer>

<!-- Footer ends -->

<!-- Scroll to top -->
<span class="totop"><a href="#"><i class="fa fa-chevron-up"></i></a></span> 

{!! Html::script('js/admin/respond.min.js') !!}
<!--[if lt IE 9]>
{!! Html::script('js/admin/html5shiv.js') !!}
<![endif]-->

<!-- JS -->
{!! Html::script('js/jquery.js') !!} <!-- jQuery -->
{!! Html::script('js/bootstrap.min.js') !!} <!-- Bootstrap -->
{!! Html::script('js/jquery-ui.min.js') !!} <!-- jQuery UI -->
{!! Html::script('js/admin/moment.min.js') !!} <!-- Moment js for full calendar -->
{!! Html::script('js/admin/fullcalendar.min.js') !!} <!-- Full Google Calendar - Calendar -->
{!! Html::script('js/jquery.rateit.min.js') !!} <!-- RateIt - Star rating -->
{!! Html::script('js/admin/jquery.prettyPhoto.js') !!} <!-- prettyPhoto -->
{!! Html::script('js/admin/jquery.slimscroll.min.js') !!} <!-- jQuery Slim Scroll -->
{!! Html::script('js/admin/jquery.dataTables.min.js') !!} <!-- Data tables -->

<!-- jQuery Flot -->
{!! Html::script('js/admin/excanvas.min.js') !!}
{!! Html::script('js/admin/jquery.flot.js') !!}
{!! Html::script('js/admin/jquery.flot.resize.js') !!}
{!! Html::script('js/admin/jquery.flot.pie.js') !!}
{!! Html::script('js/admin/jquery.flot.stack.js') !!}
{!! Html::script('js/admin/jquery.flot.time.js') !!}

<!-- jQuery Notification - Noty -->
{!! Html::script('js/admin/jquery.noty.js') !!} <!-- jQuery Notify -->
{!! Html::script('js/admin/themes/default.js') !!} <!-- jQuery Notify -->
{!! Html::script('js/admin/layouts/bottom.js') !!} <!-- jQuery Notify -->
{!! Html::script('js/admin/layouts/topRight.js') !!} <!-- jQuery Notify -->
{!! Html::script('js/admin/layouts/top.js') !!} <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

{!! Html::script('js/admin/sparklines.js') !!} <!-- Sparklines -->
{{--{!! Html::script('js/admin/jquery.cleditor.min.js') !!} <!-- CLEditor -->--}}
{!! Html::script('js/admin/bootstrap-datetimepicker.min.js') !!} <!-- Date picker -->
{!! Html::script('js/admin/jquery.onoff.min.js') !!} <!-- Bootstrap Toggle -->
{!! Html::script('js/admin/filter.js') !!} <!-- Filter for support page -->
{!! Html::script('js/admin/custom.js') !!} <!-- Custom codes -->

resources/views/admin/partials/head.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<!-- Title and other stuffs -->
<title>{{ isset($title) ? $title : config('app.name', 'Online Catalog') }} | Admin</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">

<!-- Stylesheets -->
{!! Html::style('css/bootstrap.min.css') !!}
<!-- Font awesome icon -->
 {!! Html::style('css/font-awesome.min.css') !!}
{!! Html::style('css/font-awesome-animation.min.css') !!}

<!-- jQuery UI -->
{!! Html::style('css/font-awesome.css') !!}
<!-- Calendar -->
{!! Html::style('css/admin/fullcalendar.css') !!}
<!-- prettyPhoto -->
{!! Html::style('css/admin/prettyPhoto.css') !!}
<!-- Star rating -->
{!! Html::style('css/admin/rateit.css') !!}
<!-- Date picker -->
{!! Html::style('css/admin/bootstrap-datetimepicker.min.css') !!}
<!-- CLEditor -->
{!! Html::style('css/admin/jquery.cleditor.css') !!}
<!-- Data tables -->
{!! Html::style('css/admin/jquery.dataTables.css') !!}
<!-- Bootstrap toggle -->
{!! Html::style('css/admin/jquery.onoff.css') !!}
<!-- Main stylesheet -->
{!! Html::style('css/admin/style.css') !!}
<!-- Widgets stylesheet -->
{!! Html::style('css/admin/widgets.css') !!}

<!-- Favicon -->
<link rel="shortcut icon" href="img/favicon/favicon.png">

@yield('head_styles')

resources/views/admin/partials/header.blade.php
<header>
  <div class="container">
    <div class="row">
      <!-- Logo section -->
      <div class="col-md-4">
        <!-- Logo. -->
        <div class="logo">
          <h1>
            <a href="{{ route('admin.index') }}">
              @if(Setting::get('site_name'))
                {{ Setting::get('site_name') }}
              @else
                {{ config('app.name', trans('admin_header.title')) }}
              @endif
            </a>
          </h1>
          <p class="meta">
            @if(Setting::get('site_description'))
              {{ Setting::get('site_description') }}
            @else
              {{ trans('admin_header.description') }}
            @endif
          </p>
        </div>
        <!-- Logo ends -->
      </div>

      <!-- Button section -->
      <div class="col-md-4">

        <!-- Buttons -->
        <ul class="nav nav-pills">
          <!-- Comment button with number of latest comments count -->
          <li class="pull-right">
            <a href="{{ route('admin.comment.index') }}">
              <i class="fa fa-comments"></i> {{ trans('admin_header.comments') }} <span class="label label-info">{{ $unchecked_comments_count }}</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- Data section -->
      <div class="col-md-4">
        <div class="header-data">

          <div class="hdata">
            <div class="mcol-left">
              <i class="fa fa-shopping-cart bgreen"></i>
            </div>
            <div class="mcol-right">
              <p><a href="#">{{ $shops_count }}</a><em>{{ trans('admin_header.shops') }}</em></p>
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="hdata">
            <div class="mcol-left">
              <i class="fa fa-tags bblue"></i>
            </div>
            <div class="mcol-right">
              <p><a href="#">{{ $products_count }}</a> <em>{{ trans('admin_header.products') }}</em></p>
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="hdata">
            <div class="mcol-left">
              <i class="fa fa-tags bred"></i>
            </div>
            <div class="mcol-right">
              <p><a href="#">{{ $categories_count }}</a> <em>{{ trans('admin_header.categories') }}</em></p>
            </div>
            <div class="clearfix"></div>
          </div>

        </div>
      </div>
    </div>
  </div>
</header>

resources/views/admin/partials/right_form_image.blade.php
<div class="col-md-4">
    <div class="widget">
        <div class="widget-head">
          <div class="pull-left">{{ trans('common.image') }}</div>
          <div class="widget-icons pull-right">
            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="widget-content">
            <div class="padd">
                <div class="form">
                    <div class="form-group">
                        <a href="#selectImageModal" data-toggle="modal" class="btn btn-info col-sm-12">
                            {{ trans('common.select_image') }}
                        </a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <a href="#uploadImageModal" data-toggle="modal" class="btn btn-info col-sm-12">
                            {{ trans('common.upload_image') }}
                        </a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <div class="thumbnail col-sm-12 selected-image">
                            <a id="remove-selected-image" href="javascript:void(0);" class="close">
                                &#10006;
                            </a>
                            @if(isset($record) && $record->image)
                                {!! HTML::image($record->image->url, 'selected image') !!}
                            @else
                                {!! HTML::image('assets/img/no-image.png', 'selected image') !!}
                            @endif
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    {!! Form::hidden('image_id', (isset($record) && $record->image) ? $record->image->id : 0) !!}
                </div>
            </div>
            <div class="widget-foot">
            <!-- Footer goes here -->
            </div>
        </div>
    </div>
</div>

resources/views/admin/partials/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-dropdown"><a href="#">{{ trans('admin_sidebar.navigation') }}</a></div>

    <!--- Sidebar navigation -->
    <!-- If the main navigation has sub navigation, then add the class "has_sub" to "li" of main navigation. -->
    <ul id="nav">
      <!-- Main menu with font awesome icon -->
      <li @if(Request::segment(2) == 'index') class="open" @endif>
        <a href="{{ route('admin.index') }}"><i class="fa fa-home"></i> {{ trans('admin_sidebar.dashboard') }}</a>
      </li>
      <li @if(Request::segment(2) == 'user') class="open" @endif>
        <a href="{{ route('admin.user.index') }}"><i class="fa fa-user"></i> {{ trans('admin_sidebar.users') }}</a>
      </li>
      <li class="has_sub @if(in_array(Request::segment(2), ['product', 'category', 'log'])) open @endif" >
          <a href="#"><i class="fa fa-tags"></i> {{ trans('admin_sidebar.catalog') }}</a>
          <ul>
              <li @if(Request::segment(2) == 'product') class="current" @endif>
                  <a href="{{ route('admin.product.index') }}"><i class="fa fa-tags"></i> {{ trans('admin_sidebar.products') }}</a>
              </li>
              <li @if(Request::segment(2) == 'category') class="current" @endif>
                  <a href="{{ route('admin.category.index') }}"><i class="fa fa-tag"></i> {{ trans('admin_sidebar.categories') }}</a>
              </li>
              <li @if(Request::segment(2) == 'log') class="current" @endif>
                  <a href="{{ route('admin.log.index') }}"><i class="fa fa-clock-o"></i> {{ trans('admin_sidebar.logs') }}</a>
              </li>
          </ul>
      </li>
      <li @if(Request::segment(2) == 'shop') class="open" @endif>
        <a href="{{ route('admin.shop.index') }}"><i class="fa fa-shopping-cart"></i> {{ trans('admin_sidebar.shops') }}</a>
      </li>
      <li class="has_sub @if(Request::segment(2) == 'attribute_set' || Request::segment(2) == 'attribute') open @endif" >
        <a href="#"><i class="fa fa-cubes"></i> {{ trans('admin_sidebar.attributes') }}</a>
        <ul>
            <li @if(Request::segment(2) == 'attribute') class="current" @endif>
              <a href="{{ route('admin.attribute.index') }}"><i class="fa fa-cubes"></i> {{ trans('admin_sidebar.attributes') }}</a>
            </li>
            <li @if(Request::segment(2) == 'attribute_set') class="current" @endif>
              <a href="{{ route('admin.attribute_set.index') }}"><i class="fa fa-cube"></i> {{ trans('admin_sidebar.attribute_sets') }}</a>
            </li>
        </ul>
      </li>
      <li class="has_sub @if(in_array(Request::segment(2), ['article', 'section', 'comment', 'tag'])) open @endif" >
          <a href="#"><i class="fa fa-newspaper-o"></i> {{ trans('admin_sidebar.blog') }}</a>
          <ul>
              <li @if(Request::segment(2) == 'article') class="current" @endif>
                  <a href="{{ route('admin.article.index') }}"><i class="fa fa-newspaper-o"></i> {{ trans('admin_sidebar.articles') }}</a>
              </li>
              <li @if(Request::segment(2) == 'section') class="current" @endif>
                  <a href="{{ route('admin.section.index') }}"><i class="fa fa-object-group"></i> {{ trans('admin_sidebar.sections') }}</a>
              </li>
              <li @if(Request::segment(2) == 'comment') class="current" @endif>
                  <a href="{{ route('admin.comment.index') }}"><i class="fa fa-comments-o"></i> {{ trans('admin_sidebar.comments') }}</a>
              </li>
              <li @if(Request::segment(2) == 'tag') class="current" @endif>
                  <a href="{{ route('admin.tag.index') }}"><i class="fa fa-tags"></i> {{ trans('admin_sidebar.tags') }}</a>
              </li>
          </ul>
      </li>
      <li @if(Request::segment(2) == 'page') class="open" @endif>
          <a href="{{ route('admin.page.index') }}"><i class="fa fa-file"></i> {{ trans('admin_sidebar.pages') }}</a>
      </li>
      <li @if(Request::segment(2) == 'menu') class="open" @endif>
          <a href="{{ route('admin.menu.index') }}"><i class="fa fa-list"></i> {{ trans('admin_sidebar.menus') }}</a>
      </li>
      <li @if(Request::segment(2) == 'setting') class="open" @endif>
          <a href="{{ route('admin.setting.index') }}"><i class="fa fa-gears"></i> {{ trans('admin_sidebar.settings') }}</a>
      </li>
      <li class="has_sub @if(in_array(Request::segment(2), ['stat'])) open @endif" >
          <a href="#"><i class="fa fa-clock-o"></i> {{ trans('admin_sidebar.stats') }}</a>
          <ul>
              <li @if(Request::segment(3) == 'products') class="current" @endif>
                  <a href="{{ route('admin.stat.products') }}"><i class="fa fa-tags"></i> {{ trans('admin_sidebar.products') }}</a>
              </li>
              <li @if(Request::segment(3) == 'shops') class="current" @endif>
                  <a href="{{ route('admin.stat.shops') }}"><i class="fa fa-shopping-cart"></i> {{ trans('admin_sidebar.shops') }}</a>
              </li>
              <li @if(Request::segment(3) == 'articles') class="current" @endif>
                  <a href="{{ route('admin.stat.articles') }}"><i class="fa fa-newspaper-o"></i> {{ trans('admin_sidebar.articles') }}</a>
              </li>
          </ul>
      </li>
    </ul>
</div>

resources/views/admin/partials/success.blade.php
@if (Session::has('success'))
    <div class="alert alert-success alert-dismissible">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <div><i class="icon fa fa-check"></i> {{ session('success') }}</div>
    </div>
@endif